In [1]:
import pandas as p

In [2]:
df = p.read_csv('data.csv')
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [3]:
df["Value_new"] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

         Date Category  Value   Product  Sales Region  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         28
1  2023-01-02        B   39.0  Product3  110.0  North         39
2  2023-01-03        C   32.0  Product2  398.0   East         32
3  2023-01-04        B    8.0  Product1  522.0   East          8
4  2023-01-05        B   26.0  Product3  869.0  North         26

In [4]:
df['New_Value'] = df['Value'].apply(lambda x:x*2)
df.head()

         Date Category  Value   Product  Sales Region  Value_new  New_Value
0  2023-01-01        A   28.0  Product1  754.0   East         28       56.0
1  2023-01-02        B   39.0  Product3  110.0  North         39       78.0
2  2023-01-03        C   32.0  Product2  398.0   East         32       64.0
3  2023-01-04        B    8.0  Product1  522.0   East          8       16.0
4  2023-01-05        B   26.0  Product3  869.0  North         26       52.0

In [5]:
grouped_mean = df.groupby('Product')["Value"].mean()
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [6]:
grouped_sum = df.groupby(['Product','Region'])["Value"].sum()
grouped_sum

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [7]:
grouped_sum = df.groupby(['Region','Product'])["Value"].sum()
grouped_sum

Region  Product
East    Product1    292.0
        Product2     56.0
        Product3    202.0
North   Product1      9.0
        Product2    127.0
        Product3    203.0
South   Product1    100.0
        Product2    181.0
        Product3    215.0
West    Product1    246.0
        Product2    428.0
        Product3    373.0
Name: Value, dtype: float64

In [8]:
df1 = p.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = p.DataFrame({'Key': ['A','B','D'], 'Value2':[4,5,6]})

In [9]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [10]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [11]:
p.merge(df1,df2,on='Key',how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [12]:
p.merge(df1,df2,on='Key',how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [13]:
p.merge(df1,df2,on='Key',how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [14]:
p.merge(df1,df2,on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0